[package]
name = "rust_aes"
version = "0.1.0"
authors = ["Patrick Breen <breen.patrick.1010@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.3.4"
rand = "0.7.3"