[package]
name = "cpu_emulator"
version = "0.1.0"
authors = ["Patrick Breen <breen.patrick@gmail.com>"]

[dependencies]
piston = "0.49.0"
piston_window = "0.103.0"
rand = "0.7.0"
vecmath = "1.0.0"
image = "0.22.1"